-- MySQL Script generated by MySQL Workbench
-- Sun Nov 15 15:13:53 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tododb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tododb` ;

-- -----------------------------------------------------
-- Schema tododb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tododb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tododb` ;

-- -----------------------------------------------------
-- Table `tododb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tododb`.`user` ;

CREATE TABLE IF NOT EXISTS `tododb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dob` DATE NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tododb`.`todo_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tododb`.`todo_item` ;

CREATE TABLE IF NOT EXISTS `tododb`.`todo_item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `datetime_created` DATETIME NOT NULL,
  `datetime_last_updated` DATETIME NULL,
  PRIMARY KEY (`item_id`, `user_id`),
  INDEX `fk_todo_item_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_todo_item_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tododb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Triggers for item datetime created/update fields
-- -----------------------------------------------------
CREATE TRIGGER `todo_item_datetime_created` BEFORE INSERT ON  `todo_item` 
FOR EACH ROW SET NEW.datetime_created = NOW();

CREATE TRIGGER `todo_item_datetime_last_updated` BEFORE UPDATE ON  `todo_item` 
FOR EACH ROW SET NEW.datetime_last_updated = NOW();


-- -----------------------------------------------------
-- Insert and Update statements for testing
-- -----------------------------------------------------

INSERT INTO `tododb`.`user` 
VALUES (NULL, 'matt-jarvis', 'passpasspass', 'Matthew', 'Jarvis', '1991-07-13');

SET @user = LAST_INSERT_ID();

INSERT INTO `tododb`.`todo_item` (`user_id`, `title`, `description`)
VALUES (@user, 'Shopping', 'Milk, bread and cheese');

SELECT * FROM `tododb`.`todo_item`;
DO SLEEP(5);

UPDATE `tododb`.`todo_item` 
SET `description`= 'Milk, bread, cheese and bacon'
WHERE `user_id` = @user;

SELECT * FROM `tododb`.`todo_item`;
